(() => {
  "use strict";
  const normalize=value=>String(value??"").normalize("NFKC").toLowerCase().replace(/[ァ-ヶ]/g,character=>String.fromCharCode(character.charCodeAt(0)-0x60)).replace(/[\s　・,，.。/／_＿\-ー!?！？「」『』（）()【】\[\]]/g,"");
  const searchable=item=>["published","verified"].includes(item.publicationStatus)&&["published","verified"].includes(item.verificationStatus)&&!['needs_review','source_unreachable','draft','unverified','fixture'].includes(item.freshnessStatus)&&/^https:\/\//.test(item.url||"");
  const variants=(query,groups)=>{const normalized=normalize(query);if(!normalized)return[];const values=new Set([normalized]);for(const group of groups||[]){const normalizedGroup=group.map(normalize);if(normalizedGroup.some(word=>normalized.includes(word)||word.includes(normalized)))normalizedGroup.forEach(word=>values.add(word))}return [...values]};
  const scoreItem=(item,queryVariants,municipalityId)=>{const title=normalize(item.title),keywords=(item.keywords||[]).map(normalize),summary=normalize(item.summary);let score=0;for(const query of queryVariants){if(title===query)score=Math.max(score,400);else if(title.includes(query))score=Math.max(score,300);if(keywords.includes(query))score=Math.max(score,250);else if(keywords.some(word=>word.includes(query)||query.includes(word)))score=Math.max(score,200);if(summary.includes(query))score=Math.max(score,100)}if(!score)return 0;if(municipalityId&&item.municipalityId===municipalityId)score+=50;if(item.freshnessStatus==="current")score+=10;if(item.freshnessStatus==="expired")score-=80;return score};
  const search=(items,query,municipalityId,groups)=>{const queryVariants=variants(query,groups);if(!queryVariants.length)return[];const seen=new Set();return (items||[]).filter(searchable).map(item=>({item,score:scoreItem(item,queryVariants,municipalityId)})).filter(result=>result.score>0&&!seen.has(result.item.url)&&(seen.add(result.item.url),true)).sort((a,b)=>b.score-a.score||String(b.item.publishedAt||b.item.updatedAt||"").localeCompare(String(a.item.publishedAt||a.item.updatedAt||""))||a.item.title.localeCompare(b.item.title,"ja")).map(result=>result.item)};
  const clean=value=>String(value??"").replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]);
  window.ReconstructionOfficialSearch={normalize,variants,search,searchable,scoreItem};
  const root=document.querySelector("[data-official-search-form]");if(!root)return;
  const keyword=root.querySelector("[data-search-keyword]"),municipality=root.querySelector("[data-search-municipality]"),status=document.querySelector("[data-search-status]"),resultsRoot=document.querySelector("[data-search-results]"),heading=document.querySelector("#search-results-title"),more=document.querySelector("[data-search-more]");
  let indexPromise,synonymsPromise,currentResults=[],visible=15;
  const loadIndex=()=>indexPromise||=fetch("public-data/reconstruction/official-search-index.json",{credentials:"same-origin"}).then(response=>response.ok?response.json():Promise.reject(Error("index")));
  const loadSynonyms=()=>synonymsPromise||=fetch("config/reconstruction-search-synonyms.json",{credentials:"same-origin"}).then(response=>response.ok?response.json():({groups:[]})).catch(()=>({groups:[]}));
  fetch("data/reconstruction/municipalities.json",{credentials:"same-origin"}).then(response=>response.ok?response.json():[]).then(items=>{municipality.insertAdjacentHTML("beforeend",items.map(item=>`<option value="${clean(item.id)}">${clean(item.name)}</option>`).join(""));const requested=new URLSearchParams(location.search).get("municipality");if(items.some(item=>item.id===requested))municipality.value=requested}).catch(()=>{});
  const date=value=>value?String(value).slice(0,10).replaceAll("-","/"):"日付は公式ページで確認";
  const card=item=>`<li class="official-search-card"><div class="official-search-card__labels"><span>公式情報</span><span>${clean(item.governmentLevel)}</span>${item.freshnessStatus==="expired"?'<span>受付終了・過去情報</span>':""}</div><h3>${clean(item.title)}</h3><p><strong>発表主体：</strong>${clean(item.organizationName)}${item.municipalityName?` / ${clean(item.municipalityName)}`:""}</p><p>${clean(item.summary)}</p><small>${item.publishedAt?"発表日":"更新・確認日"}：${clean(date(item.publishedAt||item.updatedAt||item.retrievedAt))}</small><a href="${clean(item.url)}" target="_blank" rel="noopener noreferrer">公式サイトで確認 <span aria-hidden="true">↗</span></a></li>`;
  const render=()=>{const shown=currentResults.slice(0,visible);resultsRoot.innerHTML=shown.length?`<ul class="official-search-list">${shown.map(card).join("")}</ul>`:"";more.hidden=currentResults.length<=visible};
  async function performSearch({moveFocus=true}={}){const query=keyword.value.slice(0,50);if(!normalize(query)){currentResults=[];resultsRoot.innerHTML='<div class="search-empty"><h3>短い検索語を入力してください</h3><p>文字や数字を含む言葉で検索できます。</p></div>';status.textContent="検索語が入力されていません。";more.hidden=true;if(moveFocus)heading.focus();return}status.textContent="公式情報を検索しています。";try{const [index,synonyms]=await Promise.all([loadIndex(),loadSynonyms()]);currentResults=search(index.items,query,municipality.value,synonyms.groups);visible=15;if(currentResults.length){status.textContent=`${currentResults.length}件見つかりました。${municipality.value?"選択した自治体の情報を先に表示しています。":""}`;render()}else{status.textContent="この検索では、掲載中の公式情報を見つけられませんでした。";resultsRoot.innerHTML='<div class="search-empty"><h3>掲載中の公式情報を見つけられませんでした</h3><p>支援制度や公式情報が存在しないという意味ではありません。</p><div class="search-empty-links"><button type="button" data-refocus-search>言葉を変えて探す</button><a href="reconstruction.html#organizer">暮らしの困りごとから探す</a><a href="municipalities.html">自治体の災害関連公式情報を見る</a></div></div>';resultsRoot.querySelector("[data-refocus-search]")?.addEventListener("click",()=>keyword.focus());more.hidden=true}}catch{currentResults=[];status.textContent="検索データを読み込めませんでした。";resultsRoot.innerHTML='<div class="search-empty"><h3>公式情報を読み込めませんでした</h3><p>支援や公式情報がないという意味ではありません。</p><div class="search-empty-links"><a href="reconstruction.html#organizer">暮らしの困りごとから探す</a><a href="municipalities.html">自治体の災害関連公式情報を見る</a></div></div>';more.hidden=true}if(moveFocus)heading.focus()}
  root.addEventListener("submit",event=>{event.preventDefault();performSearch()});root.querySelector("[data-search-clear]")?.addEventListener("click",()=>{keyword.value="";currentResults=[];resultsRoot.innerHTML="";status.textContent="知りたい言葉を入力すると、掲載中の公式情報を検索できます。";more.hidden=true;keyword.focus()});root.querySelectorAll("[data-search-example]").forEach(button=>button.addEventListener("click",()=>{keyword.value=button.dataset.searchExample;performSearch()}));municipality.addEventListener("change",()=>{if(normalize(keyword.value))performSearch({moveFocus:false})});more.addEventListener("click",()=>{visible+=15;render();more.focus()});
})();
