(()=>{
  "use strict";
  const button=document.querySelector("[data-site-search-open]");if(!button)return;
  const groups=[["罹災証明","り災証明","りさい証明","罹災","りさい"],["家","住宅","住まい","住居"],["修理","修繕","直す","なおす"],["税","税金","市税","減免"],["水","水道","断水","給水"],["ごみ","ゴミ","災害ごみ","廃棄物","片付け"],["仕事","雇用","就労","失業","休業"],["会社","事業","事業者","店舗"],["介護","高齢者","福祉"],["薬","医療","診療","病院"],["学校","子ども","こども","保育","教育"],["生活費","支払い","支援金","貸付","給付","お金"],["避難所","避難場所","避難"],["ボランティア","災害vc","支援活動"],["問い合わせ","問合せ","相談","連絡先"]];
  const normalize=value=>String(value??"").normalize("NFKC").toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).replace(/[\s　・,，.。/／_＿\-ー!?！？「」『』（）()【】\[\]]/g,"");
  const clean=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const variants=query=>{const q=normalize(query),values=new Set([q]);groups.forEach(group=>{const words=group.map(normalize);if(words.some(word=>word.includes(q)||q.includes(word)))words.forEach(word=>values.add(word))});return [...values].filter(Boolean)};
  const bigrams=value=>{const q=normalize(value),result=[];for(let i=0;i<q.length-1;i++)result.push(q.slice(i,i+2));return result};
  const similarity=(left,right)=>{if(left===right)return 1;const a=bigrams(left),b=bigrams(right);if(!a.length||!b.length)return 0;const pool=[...b];let hits=0;a.forEach(pair=>{const index=pool.indexOf(pair);if(index>=0){hits++;pool.splice(index,1)}});return 2*hits/(a.length+b.length)};
  const score=(item,query)=>{const words=variants(query),title=normalize(item.title),description=normalize(item.description),headings=(item.headings||[]).map(normalize);let best=0;for(const word of words){if(title===word)best=Math.max(best,1000);else if(title.startsWith(word))best=Math.max(best,850);else if(title.includes(word))best=Math.max(best,760);if(headings.some(value=>value===word))best=Math.max(best,720);else if(headings.some(value=>value.includes(word)||word.includes(value)))best=Math.max(best,620);if(description.includes(word))best=Math.max(best,420);if(word.length>=3){const fuzzy=Math.max(similarity(word,title),...headings.map(value=>similarity(word,value)));if(fuzzy>=.7)best=Math.max(best,Math.round(500*fuzzy));else if(fuzzy>=.52)best=Math.max(best,Math.round(300*fuzzy))}}return best};
  let indexPromise;const load=()=>indexPromise||=fetch("public-data/site-search-index.json",{credentials:"same-origin"}).then(response=>response.ok?response.json():Promise.reject(Error("index")));
  document.body.insertAdjacentHTML("beforeend",`<div class="site-search-layer" data-site-search-layer hidden><div class="site-search-backdrop" data-site-search-close></div><section class="site-search-dialog" role="dialog" aria-modal="true" aria-labelledby="site-search-title"><header><div><span>サイト内検索</span><h2 id="site-search-title">知りたい情報を探す</h2></div><button type="button" data-site-search-close aria-label="検索を閉じる">×</button></header><label for="site-search-input">言葉を入力してください</label><div class="site-search-input"><span aria-hidden="true">⌕</span><input id="site-search-input" type="search" maxlength="50" autocomplete="off" spellcheck="false" placeholder="例：り災証明、家の修理、断水"><button type="button" data-site-search-clear>消す</button></div><p class="site-search-help">文字を入力すると、関連するページがすぐ下に表示されます。ひらがなや少し違う言い方でも探せます。</p><div class="site-search-status" data-site-search-status aria-live="polite">検索する言葉を入力してください。</div><div class="site-search-results" data-site-search-results></div><p class="site-search-privacy">入力した言葉は保存・送信されません。氏名・住所・電話番号は入力しないでください。</p></section></div>`);
  const layer=document.querySelector("[data-site-search-layer]"),input=layer.querySelector("input"),status=layer.querySelector("[data-site-search-status]"),results=layer.querySelector("[data-site-search-results]");let previousFocus=button,timer=0,composing=false;
  const close=()=>{layer.hidden=true;document.body.classList.remove("site-search-open");button.setAttribute("aria-expanded","false");previousFocus?.focus()};
  const run=async()=>{const query=input.value.slice(0,50);if(!normalize(query)){status.textContent="検索する言葉を入力してください。";results.innerHTML="";return}status.textContent="検索しています。";try{const data=await load();const found=(data.items||[]).map(item=>({item,value:score(item,query)})).filter(result=>result.value>0).sort((a,b)=>b.value-a.value||a.item.title.localeCompare(b.item.title,"ja")).slice(0,8).map(result=>result.item);status.textContent=found.length?`${found.length}件の候補があります。`:`「${query}」に近いページは見つかりませんでした。`;results.innerHTML=found.length?`<ul>${found.map(item=>`<li><a href="${clean(item.url)}"><span>${clean(item.category)}</span><b>${clean(item.title)}</b><small>${clean(item.description)}</small><i aria-hidden="true">→</i></a></li>`).join("")}</ul>`:`<div class="site-search-empty"><b>近いページが見つかりませんでした</b><p>短い言葉に変えてお試しください。例：「住宅修理」→「修理」</p></div>`}catch{status.textContent="検索データを読み込めませんでした。";results.innerHTML='<div class="site-search-empty"><b>ページを再読み込みして、もう一度お試しください。</b></div>'}};
  const schedule=()=>{clearTimeout(timer);timer=setTimeout(run,90)};button.addEventListener("click",()=>{previousFocus=document.activeElement;layer.hidden=false;document.body.classList.add("site-search-open");button.setAttribute("aria-expanded","true");requestAnimationFrame(()=>input.focus());if(normalize(input.value))run()});layer.querySelectorAll("[data-site-search-close]").forEach(item=>item.addEventListener("click",close));layer.querySelector("[data-site-search-clear]").addEventListener("click",()=>{input.value="";run();input.focus()});input.addEventListener("compositionstart",()=>composing=true);input.addEventListener("compositionend",()=>{composing=false;schedule()});input.addEventListener("input",()=>{if(!composing)schedule()});layer.addEventListener("keydown",event=>{if(event.key==="Escape")close();if(event.key==="ArrowDown"&&document.activeElement===input){event.preventDefault();results.querySelector("a")?.focus()}});
})();
