(()=>{
const terms=window.GLOSSARY||[];
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let category="すべて";
const categories=["すべて",...new Set(terms.map(t=>t.cat))];
const links=t=>`${t.related?`<a href="${t.related[1]}">${esc(t.related[0])} →</a>`:""}${t.official?`<a href="${t.official[1]}" target="_blank" rel="noopener">${esc(t.official[0])} ↗</a>`:""}<button type="button" data-copy="${t.id}">この用語へのリンクをコピー</button>`;
const render=()=>{const q=$("#termSearch").value.trim().toLowerCase();const found=terms.filter(t=>(category==="すべて"||t.cat===category)&&`${t.term} ${t.reading} ${t.short} ${t.body} ${t.diff||""}`.toLowerCase().includes(q));$("#termCount").textContent=found.length;$("#termNoResults").hidden=found.length>0;$("#termList").innerHTML=found.map(t=>`<details id="${t.id}" class="term-card"><summary><span class="term-category">${t.cat}</span><div><h2>${esc(t.term)}</h2><p>${esc(t.short)}</p></div><i>＋</i></summary><div class="term-body"><p>${esc(t.body)}</p>${t.diff?`<aside><b>混同しやすい点</b><span>${esc(t.diff)}</span></aside>`:""}<div class="term-links">${links(t)}</div></div></details>`).join("");document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const url=`${location.href.split('#')[0]}#${b.dataset.copy}`;try{await navigator.clipboard.writeText(url);b.textContent="コピーしました"}catch{location.hash=b.dataset.copy}});openHash()};
const renderCategories=()=>{$("#termCategories").innerHTML=categories.map(c=>`<button type="button" class="${c===category?"active":""}" data-category="${c}">${c}</button>`).join("");document.querySelectorAll('#termCategories button').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderCategories();render()})};
const openHash=()=>{if(!location.hash)return;const el=document.querySelector(location.hash);if(el){el.open=true;setTimeout(()=>el.scrollIntoView({block:"start"}),0)}};$("#termSearch").addEventListener("input",render);window.addEventListener("hashchange",openHash);renderCategories();render();
})();
