(()=>{
const terms=[
{id:"shindo",term:"震度",reading:"しんど",cat:"地震",short:"その場所での揺れの強さ",body:"観測地点ごとの揺れの強さを0から7までの10段階で表します。同じ地震でも場所により震度は異なります。",diff:"マグニチュードは地震そのものの規模です。",official:["気象庁 地震情報","https://www.jma.go.jp/jma/kishou/know/jishin/joho/seisinfo.html"],related:["時系列","timeline.html"]},
{id:"magnitude",term:"マグニチュード",reading:"まぐにちゅーど M",cat:"地震",short:"地震そのものの規模",body:"地震が放出するエネルギーの規模を表す指標です。値が同じでも、震源からの距離や地盤により各地の震度は変わります。",diff:"震度は各地点で実際に観測された揺れの強さです。",official:["気象庁 マグニチュード","https://www.jma.go.jp/jma/kishou/know/jishin/joho/info_magnitude.html"],related:["時系列","timeline.html"]},
{id:"hypocenter",term:"震源・震央",reading:"しんげん しんおう",cat:"地震",short:"地震が始まった場所と、その真上の地表点",body:"震源は地下で岩盤の破壊が始まった場所、震央は震源の真上にあたる地表上の地点です。",official:["気象庁 地震情報","https://www.jma.go.jp/jma/kishou/know/jishin/joho/seisinfo.html"]},
{id:"eew",term:"緊急地震速報",reading:"きんきゅうじしんそくほう",cat:"地震",short:"強い揺れの到達を予測して知らせる情報",body:"地震波を素早く解析し、強い揺れが予想される地域へ知らせます。発表から揺れまで時間がない場合や、揺れに間に合わない場合もあります。",official:["気象庁 緊急地震速報","https://www.jma.go.jp/jma/kishou/know/jishin/eew/shikumi/shousai.html"]},
{id:"aftershock",term:"余震・地震活動",reading:"よしん じしんかつどう",cat:"地震",short:"大きな地震後も続く周辺の地震",body:"大きな地震の後は、同じ周辺で地震が続くことがあります。回数が減っても強い揺れが起こる可能性があるため、危険な建物や斜面に近づかないことが重要です。",official:["気象庁 地震FAQ","https://www.jma.go.jp/jma/kishou/know/faq/faq7.html"]},
{id:"long-period",term:"長周期地震動",reading:"ちょうしゅうきじしんどう",cat:"地震",short:"高層建物などを長く大きく揺らす地震動",body:"周期の長いゆっくりした揺れで、高層建物では震源から遠くても長時間大きく揺れることがあります。",official:["気象庁 長周期地震動","https://www.jma.go.jp/jma/kishou/know/jishin/choshuki/choshuki_eq1.html"]},
{id:"alert-level",term:"警戒レベル",reading:"けいかいれべる",cat:"避難",short:"避難行動を5段階で示す目安",body:"レベル3は高齢者等避難、レベル4は避難指示、レベル5は緊急安全確保です。危険な場所にいる人はレベル4までに避難します。",official:["内閣府 避難情報ガイドライン","https://www.bousai.go.jp/oukyu/hinanjouhou/r3_hinanjouhou_guideline/index.html"],related:["稼働避難所","shelters.html"]},
{id:"elderly-evacuation",term:"高齢者等避難",reading:"こうれいしゃとうひなん",cat:"避難",short:"避難に時間がかかる人が移動を始める情報",body:"警戒レベル3。高齢者、障害のある方、乳幼児を連れた方などと、その支援者は危険な場所から避難を開始します。その他の人も準備や自主避難を検討します。",official:["内閣府 避難情報ガイドライン","https://www.bousai.go.jp/oukyu/hinanjouhou/r3_hinanjouhou_guideline/index.html"]},
{id:"evacuation-order",term:"避難指示",reading:"ひなんしじ",cat:"避難",short:"危険な場所から全員避難する情報",body:"警戒レベル4。対象地域の危険な場所にいる人は避難します。避難先は公的な避難所だけでなく、安全な親戚宅やホテルなども含みます。",diff:"現在は「避難勧告」は使われません。",official:["内閣府 避難情報ガイドライン","https://www.bousai.go.jp/oukyu/hinanjouhou/r3_hinanjouhou_guideline/index.html"],related:["稼働避難所","shelters.html"]},
{id:"emergency-safety",term:"緊急安全確保",reading:"きんきゅうあんぜんかくほ",cat:"避難",short:"すでに危険が迫る中で命を守る行動",body:"警戒レベル5。安全な避難ができない可能性がある段階です。建物の上階や崖から離れた部屋など、その時点で少しでも安全な場所へ移動します。必ず発令される情報ではありません。",official:["内閣府 避難情報ガイドライン","https://www.bousai.go.jp/oukyu/hinanjouhou/r3_hinanjouhou_guideline/index.html"]},
{id:"emergency-evacuation-place",term:"指定緊急避難場所",reading:"していきんきゅうひなんばしょ",cat:"避難",short:"災害の危険から命を守るため逃げる場所",body:"洪水、津波、土砂災害、地震など、災害の種類ごとに安全性を満たす場所です。災害の種類によっては使えない施設もあります。",diff:"指定避難所は、危険が去るまで生活するための施設です。",official:["国土地理院 避難場所の説明","https://web1.gsi.go.jp/bousaichiri/hinanbasho-help.html"]},
{id:"designated-shelter",term:"指定避難所",reading:"していひなんじょ",cat:"避難",short:"自宅に戻れない人が一時的に生活する施設",body:"災害の危険がなくなるまで、または自宅へ戻れるまで滞在するため市町村が指定した施設です。指定されていても常に開設しているわけではありません。",diff:"現在開設中かどうかは、県・市町村の最新情報で確認します。",official:["国土地理院 避難所の説明","https://web1.gsi.go.jp/bousaichiri/hinanbasho-help.html"],related:["稼働避難所","shelters.html"]},
{id:"welfare-shelter",term:"福祉避難所",reading:"ふくしひなんじょ",cat:"避難",short:"一般避難所での生活が難しい要配慮者のための避難所",body:"高齢者、障害のある方、妊産婦など、特別な配慮が必要な人を対象とする二次的な避難所です。原則として自治体の判断・調整を経て受け入れます。",related:["支援分野・福祉","support.html?category=welfare"]},
{id:"lifeline",term:"ライフライン",reading:"らいふらいん",cat:"被害",short:"生活を支える電気・水道・ガス・通信など",body:"停止戸数や復旧見込みは事業者ごとに集計方法が異なります。「停電戸数」と「事故受付件数」など、数値の定義にも注意が必要です。",related:["時系列","timeline.html"]},
{id:"damage-assessment",term:"住家の被害認定",reading:"じゅうかのひがいにんてい",cat:"被害",short:"市町村が住まいの被害程度を調査・判定",body:"国の基準に基づき、全壊、大規模半壊、中規模半壊、半壊、準半壊などを判定します。その結果が罹災証明書に記載されます。",official:["内閣府 住家の被害認定","https://www.bousai.go.jp/taisaku/unyou.html"],related:["制度・生活再建","guide.html"]},
{id:"disaster-certificate",term:"罹災証明書",reading:"りさいしょうめいしょ り災証明",cat:"被害",short:"住まいの被害程度を市町村が証明する書類",body:"支援金、住宅支援、税の減免などの申請で必要になることがあります。申請先、調査方法、交付時期は市町村へ確認します。",diff:"被災届出証明書は、被害程度を認定する書類ではありません。",official:["内閣府 住家の被害認定","https://www.bousai.go.jp/taisaku/unyou.html"],related:["制度・生活再建","guide.html"]},
{id:"emergency-risk",term:"被災建築物応急危険度判定",reading:"おうきゅうきけんどはんてい",cat:"被害",short:"余震による倒壊など、建物へ立ち入る危険を応急判定",body:"危険・要注意・調査済などの表示で二次災害を防ぎます。住家の経済的な被害程度を認定する調査ではありません。",diff:"罹災証明書の判定とは目的が異なります。",official:["内閣府 被害認定関連資料","https://www.bousai.go.jp/kaigirep/higainintei/dai1kai/index.html"],related:["制度・生活再建","guide.html"]},
{id:"disaster-relief-act",term:"災害救助法",reading:"さいがいきゅうじょほう",cat:"制度",short:"災害直後の応急的な救助を実施する法律",body:"避難所、食料、医療、生活必需品、住宅の応急修理、応急仮設住宅などを行政が実施する根拠です。被災者全員への一律給付を定める法律ではありません。",official:["内閣府 災害救助法","https://www.bousai.go.jp/oyakudachi/info_saigaikyujo.html"],related:["制度・生活再建","guide.html"]},
{id:"severe-disaster",term:"激甚災害",reading:"げきじんさいがい",cat:"制度",short:"復旧事業への国の財政支援を厚くする指定",body:"政令で指定し、自治体の復旧事業への国庫補助のかさ上げや、中小企業者への保証特例などを行います。",diff:"災害救助法とは目的・指定手続きが異なり、一律の見舞金制度ではありません。",official:["内閣府 激甚災害制度","https://www.bousai.go.jp/taisaku/gekijinhukko/index.html"],related:["制度・生活再建","guide.html"]},
{id:"reconstruction-support",term:"被災者生活再建支援制度",reading:"ひさいしゃせいかつさいけんしえん",cat:"制度",short:"著しい住家被害を受けた世帯の再建を支援",body:"制度が適用された災害で、全壊、解体、長期避難、大規模半壊など一定要件を満たす世帯が対象です。被害区分や再建方法で支給内容が変わります。",official:["内閣府 被災者生活再建支援法","https://www.bousai.go.jp/taisaku/seikatsusaiken/shiensya.html"],related:["制度・生活再建","guide.html"]},
{id:"emergency-repair",term:"住宅の応急修理",reading:"じゅうたくのおうきゅうしゅうり",cat:"制度",short:"自宅で生活を続けるための必要最小限の修理",body:"屋根、居室、台所、トイレなどを対象に、自治体が業者へ依頼して実施します。原則として現金給付ではなく、修理前の申請・相談が重要です。",official:["内閣府 災害救助法","https://www.bousai.go.jp/oyakudachi/info_saigaikyujo.html"],related:["制度・生活再建","guide.html"]},
{id:"temporary-housing",term:"応急仮設住宅",reading:"おうきゅうかせつじゅうたく みなし仮設",cat:"制度",short:"住まいを失った人への一時的な住居",body:"新たに建設する建設型と、民間賃貸住宅を活用する賃貸型（みなし仮設）があります。自治体が示す対象要件と申込方法を確認します。",official:["内閣府 被災者支援","https://www.bousai.go.jp/taisaku/hisaisyagyousei/index.html"],related:["制度・生活再建","guide.html"]},
{id:"disaster-vc",term:"災害ボランティアセンター",reading:"さいがいVC さいがいぼらんてぃあせんたー",cat:"支援",short:"被災者のニーズとボランティアをつなぐ窓口",body:"社会福祉協議会などが設置し、依頼の受付、活動調整、安全管理などを行います。募集地域・事前登録・活動内容を公式情報で確認して参加します。",related:["支援分野・ボランティア","support.html?category=volunteer"]},
{id:"dmat",term:"DMAT",reading:"でぃーまっと 災害派遣医療チーム",cat:"支援",short:"災害急性期に活動する専門的な医療チーム",body:"大規模災害などで、機動性を持って医療活動を行うため訓練されたチームです。病院支援、搬送調整、現場活動などを行います。",related:["支援分野・福祉医療","support.html?category=welfare"]},
{id:"dwat",term:"DWAT",reading:"でぃーわっと 災害派遣福祉チーム",cat:"支援",short:"避難所などで福祉的な支援を行うチーム",body:"高齢者、障害のある方、子どもなどの福祉ニーズを把握し、生活環境の改善や必要なサービスへの橋渡しを行います。",related:["支援分野・福祉医療","support.html?category=welfare"]},
{id:"push-support",term:"プッシュ型支援",reading:"ぷっしゅがたしえん",cat:"支援",short:"要請を待たず国などが物資を送り込む支援",body:"大規模災害直後、被災自治体が必要量を正確に把握できない段階に、国が必要と見込む物資を調達・輸送します。現場ニーズとの調整が必要です。",related:["支援分野・物資","support.html?category=materials"]}
];
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let category="すべて";
const categories=["すべて",...new Set(terms.map(t=>t.cat))];
const links=t=>`${t.related?`<a href="${t.related[1]}">${esc(t.related[0])} →</a>`:""}${t.official?`<a href="${t.official[1]}" target="_blank" rel="noopener">${esc(t.official[0])} ↗</a>`:""}<button type="button" data-copy="${t.id}">この用語へのリンクをコピー</button>`;
const render=()=>{const q=$("#termSearch").value.trim().toLowerCase();const found=terms.filter(t=>(category==="すべて"||t.cat===category)&&`${t.term} ${t.reading} ${t.short} ${t.body} ${t.diff||""}`.toLowerCase().includes(q));$("#termCount").textContent=found.length;$("#termNoResults").hidden=found.length>0;$("#termList").innerHTML=found.map(t=>`<details id="${t.id}" class="term-card"><summary><span class="term-category">${t.cat}</span><div><h2>${esc(t.term)}</h2><p>${esc(t.short)}</p></div><i>＋</i></summary><div class="term-body"><p>${esc(t.body)}</p>${t.diff?`<aside><b>混同しやすい点</b><span>${esc(t.diff)}</span></aside>`:""}<div class="term-links">${links(t)}</div></div></details>`).join("");document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const url=`${location.href.split('#')[0]}#${b.dataset.copy}`;try{await navigator.clipboard.writeText(url);b.textContent="コピーしました"}catch{location.hash=b.dataset.copy}});openHash()};
const renderCategories=()=>{$("#termCategories").innerHTML=categories.map(c=>`<button type="button" class="${c===category?"active":""}" data-category="${c}">${c}</button>`).join("");document.querySelectorAll('#termCategories button').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderCategories();render()})};
const openHash=()=>{if(!location.hash)return;const el=document.querySelector(location.hash);if(el){el.open=true;setTimeout(()=>el.scrollIntoView({block:"start"}),0)}};$("#termSearch").addEventListener("input",render);window.addEventListener("hashchange",openHash);renderCategories();render();
})();
